/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Hp
 */
public class comprasView extends javax.swing.JInternalFrame {

    /**
     * Creates new form comprasView
     */
    public comprasView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLCompras = new javax.swing.JLabel();
        jLIdCompra = new javax.swing.JLabel();
        jLIdProveedor = new javax.swing.JLabel();
        jTIdProveedor = new javax.swing.JTextField();
        jTIdCompra = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBListarCompras = new javax.swing.JButton();
        jBBuscarPorFecha = new javax.swing.JButton();
        jBBuscarProductosMasCompradosEntreFechas = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jBSalir = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLFechaDeCompra = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLCompras.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLCompras.setText("Compras");
        jPanel1.add(jLCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLIdCompra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLIdCompra.setText("Id Compra");
        jPanel1.add(jLIdCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 94, 141, -1));

        jLIdProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLIdProveedor.setText("Id Proveedor");
        jPanel1.add(jLIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 151, 141, -1));
        jPanel1.add(jTIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 151, 179, -1));

        jTIdCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIdCompraActionPerformed(evt);
            }
        });
        jPanel1.add(jTIdCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 91, 179, -1));

        jBGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBGuardar.setText("Guardar");
        jPanel1.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 391, 160, -1));

        jBModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBModificar.setText("Modificar");
        jPanel1.add(jBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 391, 160, -1));

        jBListarCompras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBListarCompras.setText("Listar Compras");
        jPanel1.add(jBListarCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 391, 160, -1));

        jBBuscarPorFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBBuscarPorFecha.setText("Buscar por fecha");
        jPanel1.add(jBBuscarPorFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 456, 160, -1));

        jBBuscarProductosMasCompradosEntreFechas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBBuscarProductosMasCompradosEntreFechas.setText("Buscar productos mas comprados entre fechas");
        jPanel1.add(jBBuscarProductosMasCompradosEntreFechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 456, 400, -1));
        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 261, 620, 100));

        jBSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBSalir.setText("Salir");
        jPanel1.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 160, -1));

        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 211, 179, -1));

        jLFechaDeCompra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLFechaDeCompra.setText("Fecha de compra");
        jPanel1.add(jLFechaDeCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 214, 132, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTIdCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIdCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIdCompraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarPorFecha;
    private javax.swing.JButton jBBuscarProductosMasCompradosEntreFechas;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBListarCompras;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBSalir;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLCompras;
    private javax.swing.JLabel jLFechaDeCompra;
    private javax.swing.JLabel jLIdCompra;
    private javax.swing.JLabel jLIdProveedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTIdCompra;
    private javax.swing.JTextField jTIdProveedor;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
