/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import ProvemaxEntidades.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import provemaxgrupo35.accesoDatos.*;

/**
 *
 * @author Hp
 */
public class ProveedorView extends javax.swing.JInternalFrame {

    Proveedor prov = null;
    ProveedorData pd = new ProveedorData();
    private DefaultTableModel modelo;
    private List<Proveedor> proveedores;

    public ProveedorView() {
        initComponents();
        modelo = (DefaultTableModel) jTabla.getModel();
        proveedores = pd.listarProveedores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLIdProveedor = new javax.swing.JLabel();
        jLRazonSocial = new javax.swing.JLabel();
        jLDomicilio = new javax.swing.JLabel();
        jLTelefono = new javax.swing.JLabel();
        jLMail = new javax.swing.JLabel();
        jTIdProveedor = new javax.swing.JTextField();
        jTRazonSocial = new javax.swing.JTextField();
        jTDomicilio = new javax.swing.JTextField();
        jTTelefono = new javax.swing.JTextField();
        jTMail = new javax.swing.JTextField();
        jBNuevo = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jBListar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel1.setText("Proveedores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 19, -1, -1));

        jLIdProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLIdProveedor.setText("Id de proveedor");
        jPanel1.add(jLIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 75, -1, -1));

        jLRazonSocial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLRazonSocial.setText("Razon social");
        jPanel1.add(jLRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 99, -1));

        jLDomicilio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLDomicilio.setText("Domicilio");
        jPanel1.add(jLDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 99, -1));

        jLTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLTelefono.setText("Telefono");
        jPanel1.add(jLTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 99, -1));

        jLMail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLMail.setText("Mail");
        jPanel1.add(jLMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 221, 99, -1));

        jTIdProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 72, 205, -1));

        jTRazonSocial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 205, -1));

        jTDomicilio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDomicilioActionPerformed(evt);
            }
        });
        jPanel1.add(jTDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 205, -1));

        jTTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(jTTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 205, -1));

        jTMail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMailActionPerformed(evt);
            }
        });
        jPanel1.add(jTMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 205, -1));

        jBNuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jBNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 280, 160, -1));

        jBBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 71, 92, -1));

        jBGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 280, 160, -1));

        jBSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 504, 114, -1));

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Razón Social", "Domicilio", "Telefono", "Mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 340, 701, 116));

        jBListar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBListar.setText("Listar Proveedores");
        jBListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListarActionPerformed(evt);
            }
        });
        jPanel1.add(jBListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 280, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMailActionPerformed

    private void jTDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDomicilioActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        limpiarCampos();
        
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        String input = jTIdProveedor.getText();

        if (input.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Debe ingresar un valor en el campo IdProveedor.");
        } else {
            try {
                int idProveedor = Integer.parseInt(jTIdProveedor.getText());
                prov = pd.buscarProveedor(idProveedor);
                if (prov != null) {

                    jTRazonSocial.setText(prov.getRazonSocial());
                    jTDomicilio.setText(prov.getDomicilio());
                    jTTelefono.setText(prov.getTelefono());
                    jTMail.setText(prov.getMail());

                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El id solo debe contener números");
                limpiarCampos();
            }

        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
         try {
        String razonSocial = jTRazonSocial.getText();
        String domicilio = jTDomicilio.getText();
        String telefono = jTTelefono.getText();
        String mail = jTMail.getText();

        if (razonSocial.isEmpty() || domicilio.isEmpty() || telefono.isEmpty() || mail.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No puede haber campos vacíos");
            return;
        }

        if (!razonSocial.matches(".*[a-zA-Z].*")) {
            JOptionPane.showMessageDialog(this, "La razón social debe contener al menos una letra");
            return;
        }

        if (!domicilio.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(this, "El domicilio debe contener al menos un número");
            return;
        }

        if (!telefono.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "El teléfono debe contener solo números");
            return;
        }

        if (!mail.contains("@")) {
            JOptionPane.showMessageDialog(this, "El correo electrónico debe contener un símbolo '@'");
            return;
        }

        if (prov == null) {
            prov = new Proveedor(razonSocial, domicilio, telefono, mail);
            pd.registrarProveedor(prov);
        } else {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea modificar los datos?");
            if (confirmacion == JOptionPane.YES_OPTION) {
                prov.setRazonSocial(razonSocial);
                prov.setDomicilio(domicilio);
                prov.setTelefono(telefono);
                prov.setMail(mail);
                pd.modificarProveedor(prov);
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Se ha ingresado un dato incorrecto, intente nuevamente");
        limpiarCampos();
    }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTabla.getModel();

        // Limpia la tabla eliminando todas las filas existentes
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        // Itera sobre la lista de compras y agrega filas a la tabla
        for (Proveedor todos : proveedores) {
            modelo.addRow(new Object[]{todos.getIdProveedor(), todos.getRazonSocial(), todos.getDomicilio(), todos.getTelefono(), todos.getMail()});
        }
    }//GEN-LAST:event_jBListarActionPerformed

    private void jTTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTelefonoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBListar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLDomicilio;
    private javax.swing.JLabel jLIdProveedor;
    private javax.swing.JLabel jLMail;
    private javax.swing.JLabel jLRazonSocial;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTDomicilio;
    private javax.swing.JTextField jTIdProveedor;
    private javax.swing.JTextField jTMail;
    private javax.swing.JTextField jTRazonSocial;
    private javax.swing.JTextField jTTelefono;
    private javax.swing.JTable jTabla;
    // End of variables declaration//GEN-END:variables
private void limpiarCampos() {
        jTIdProveedor.setText("");
        jTRazonSocial.setText("");
        jTDomicilio.setText("");
        jTTelefono.setText("");
        jTMail.setText("");
        prov = null;
        DefaultTableModel modelo = (DefaultTableModel) jTabla.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }
}
