/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import ProvemaxEntidades.*;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import provemaxgrupo35.accesoDatos.*;

public class StockDeProductoView extends javax.swing.JInternalFrame {

   ProductoData proDa = new ProductoData();
    private DefaultTableModel modelo;
    private List<Producto> productos;

    
    public StockDeProductoView() {
       initComponents();
        modelo = (DefaultTableModel) jTabla.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jLStock = new javax.swing.JLabel();
        jTStockMin = new javax.swing.JTextField();
        jBNueva = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLTitulo.setText("Stock de Productos");
        jPanel1.add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLStock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLStock.setText("Ingrese el Stock mínimo:");
        jPanel1.add(jLStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 94, 160, -1));

        jTStockMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTStockMinActionPerformed(evt);
            }
        });
        jPanel1.add(jTStockMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 179, -1));

        jBNueva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBNueva.setText("Nueva");
        jBNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevaActionPerformed(evt);
            }
        });
        jPanel1.add(jBNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 90, -1));

        jBBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBBuscar.setText("Buscar productos");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 150, -1));

        jBSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 160, -1));

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Producto", "Nombre", "Descripción", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTabla);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 690, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTStockMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTStockMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTStockMinActionPerformed

    private void jBNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevaActionPerformed
      limpiarCampos();
     
    }//GEN-LAST:event_jBNuevaActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
     dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
    String input = jTStockMin.getText();

if (input.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Debe ingresar un valor en el campo Stock mínimo.");
} else {
    try {
        int stock = Integer.parseInt(input);
        productos = proDa.ListarProMin(stock);
        
        DefaultTableModel modelo = (DefaultTableModel) jTabla.getModel();
        modelo.setRowCount(0); // Limpia las filas existentes en la tabla

        for (Producto stockmin : productos) {
            modelo.addRow(new Object[]{stockmin.getIdProducto(), stockmin.getNombreDelProducto(), stockmin.getDescripcion(), stockmin.getPrecio(), stockmin.getStock()});
//        if (stockmin.getStock() < stock) {
//                    String mensaje = "El producto '" + stockmin.getNombreDelProducto() + "' tiene un stock bajo (" + stockmin.getStock() + ").";
//                    JOptionPane.showMessageDialog(this, mensaje);
//        }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Se ha ingresado un dato incorrecto, intente nuevamente.");
        limpiarCampos();
    }
}
    }//GEN-LAST:event_jBBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBNueva;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLStock;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTStockMin;
    private javax.swing.JTable jTabla;
    // End of variables declaration//GEN-END:variables
private void limpiarCampos() {
          jTStockMin.setText("");

        DefaultTableModel modelo = (DefaultTableModel) jTabla.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);

}}}
